files:
  - source: /src/main/resources/assets/timetravelmod/lang/en_us.json
    translation: >-
      /src/main/resources/assets/timetravelmod/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        es-ES: es_es
        ca: ca_es
        de: de_de
        it: it_it
        fr: fr_fr
        zh-CN: zh_cn
