modLoader="javafml"
loaderVersion="[26,)" # 26 -> 1.14.2

[[mods]]
    modId="timetravelmod"
    version="${version}"
    displayName="Time Travel Mod"
    updateJSONURL="https://raw.githubusercontent.com/rdvdev2/TimeTravelMod/1.14.2/updates.json"
    issueTrackerURL="https://github.com/rdvdev2/TimeTravelMod/issues"
    displayURL="https://minecraft.curseforge.com/projects/time-travel-mod"
    logoFile="logo.png"
    credits="Thanks to marfega for the idea of the mod."
    authors="rdvdev2"
    description='''
Ever wanted to travel through time in Minecraft? Build your own time travel machine and discover a bunch of new worlds, objects and mobs!
'''

[[dependencies.timetravelmod]]
    modId="forge"
    mandatory=true
    versionRange="[26,)" # 26 -> 1.14.2
    ordering="NONE"
    side="BOTH"

[[dependencies.timetravelmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"